# Generated by Django 3.0 on 2020-06-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='ripe',
            new_name='dead',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='color',
            new_name='description',
        ),
    ]
