# Generated by Django 3.0 on 2020-06-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200622_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hit_points',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
