# Generated by Django 3.0 on 2020-06-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200622_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='monsters_killed',
            field=models.IntegerField(default='0', editable=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='dead',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
